### ISSUE TITLE
unrelated issue about a codeberg repo

### ISSUE THREAD

**Issue by leetfin** [uhwot/files#2]
Your x spotify repo on codeberg has had the releases removed due to malware. Any way I could get a copy? Thanks!

**Comment by uhwot** [comment]
[Here](https://gdrive-pub.uhwot.workers.dev/0:/XSpotify/)

**Comment by uhwot** [comment]
Oh, looks like GDrive's blocking them too lol
Uh, lemme try somewhere else

**Comment by uhwot** [comment]
Here you go

https://mega.nz/folder/ZtgCQKxA#r9KncbghKH1Ps84qK2WNuw

**Comment by leetfin** [comment]
Thanks!

**Comment by leetfin** [comment]
RIP, 1.5 doesn't open at all and 1.1 displays an empty console.
Using token 1.5 on 1.1 crashes
